/**
 * LOIN.Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LoinItem } from './loinItem';

export interface RequirementContext { 
    actors?: Array<LoinItem>;
    milestones?: Array<LoinItem>;
    reasons?: Array<LoinItem>;
}